// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Avatar, AvatarTableId } from "./tables/Avatar.sol";
import { Achievements, AchievementsData, AchievementsTableId } from "./tables/Achievements.sol";
