// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAchievementSystem {
  function setAchievement(uint32 score, uint32 stage) external;
}
