// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAvatarSystem {
  function EmojiMon_AvatarSystem_setAchievement(address playerAddress, string memory url) external;
}
